app:
    image: ehazlett/docker-demo:latest
    ports:
      - "8080"
    environment:
      - "INTERLOCK_DATA={\"hostname\":\"demo\",\"domain\":\"demo.docker.org\"}"
      - "affinity:container!=ucp-swarm-manager"
