version: "2"

services:
  wordpress:
    image: wordpress
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    networks:
      data-tier:

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      data-tier:

networks:
  data-tier:
