version: "2"

services:
  voting-app:
    image: dockersolutions/voting-voting-app:latest
    networks:
      - voteapps-web
      - voteapps-data
    ports:
      - "80"
    environment:
      - "INTERLOCK_DATA={\"hostname\":\"vote\",\"domain\":\"demo.dckr.org\"}"

  result-app:
    image: dockersolutions/voting-result:latest
    networks:
      - voteapps-web
      - voteapps-data
    ports:
      - "80"
    environment:
      - "INTERLOCK_DATA={\"hostname\":\"result\",\"domain\":\"demo.dckr.org\"}"

  redis:
    image: dockersolutions/voting-redis:latest
    networks:
      - voteapps-data
    ports: ["6379"]

  worker:
    image: dockersolutions/voting-worker:latest
    networks:
      - voteapps-data

  db:
    image: dockersolutions/voting-postgres:9.4
    networks:
      - voteapps-data
    volumes:
      - "db-data:/var/lib/postgresql/data"

networks:
  voteapps-web:
    driver: overlay
  voteapps-data:
    driver: overlay

volumes:
  db-data:
    driver: default
