voting-app:
  image: dockersolutions/voting-voting-app:latest
  ports:
    - "80"
  environment:
    - "INTERLOCK_DATA={\"hostname\":\"vote\",\"domain\":\"orca.mac\"}"

redis:
  image: dockersolutions/voting-redis:latest
  ports: ["6379"]

worker:
  image: dockersolutions/voting-worker:latest

db:
  image: dockersolutions/voting-postgres:9.4
  volumes:
    - "postgres-data:/var/lib/postgresql/data"

result-app:
  image: dockersolutions/voting-result-app:latest
  ports:
    - "80"
  environment:
    - "INTERLOCK_DATA={\"hostname\":\"result\",\"domain\":\"orca.mac\"}"
